"""
brain/planner.py — STRIX v4.0
================================
TaskPlanner: converts ANY natural language request into a
structured JSON plan that executor.py can run step by step.

How it works:
  1. User says something complex
  2. brain_core detects it's a multi-step task
  3. TaskPlanner asks llama3.1 to break it into JSON steps
  4. executor.py runs each step in order

Supported actions in plans:
  create_folder_path   — create folder at any path (not just desktop)
  create_file_at_path  — create file at any path with content
  create_desktop_folder
  create_desktop_file
  open_app
  get_system_status
  get_weather
  get_news
  llm_response         — ask LLM a question as part of a plan

Example:
  User: "Create folder E:\\MyWebsite with HTML CSS JS files"
  Plan:
    step 1 → create_folder_path  E:\\MyWebsite
    step 2 → create_file_at_path E:\\MyWebsite\\index.html  (with starter HTML)
    step 3 → create_file_at_path E:\\MyWebsite\\style.css   (with starter CSS)
    step 4 → create_file_at_path E:\\MyWebsite\\script.js   (with starter JS)
"""

import os, sys, json, re

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

# ── Starter code templates ────────────────────────────────────
STARTERS = {
    ".py": '''\
# Python program
# Generated by STRIX

def main():
    print("Hello, Boss!")

if __name__ == "__main__":
    main()
''',
    ".java": '''\
// Java program
// Generated by STRIX

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello, Boss!");
    }
}
''',
    ".html": '''\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Website</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Hello, Boss!</h1>
    <p>Your website is ready.</p>
    <script src="script.js"></script>
</body>
</html>
''',
    ".css": '''\
/* CSS Styles */
/* Generated by STRIX */

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: Arial, sans-serif;
    background-color: #0a0a0a;
    color: #ffffff;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}

h1 {
    color: #00e5ff;
    font-size: 2rem;
}
''',
    ".js": '''\
// JavaScript
// Generated by STRIX

document.addEventListener("DOMContentLoaded", function () {
    console.log("Hello, Boss! Script loaded.");
});
''',
    ".cpp": '''\
// C++ program
// Generated by STRIX

#include <iostream>
using namespace std;

int main() {
    cout << "Hello, Boss!" << endl;
    return 0;
}
''',
    ".c": '''\
/* C program */
/* Generated by STRIX */

#include <stdio.h>

int main() {
    printf("Hello, Boss!\\n");
    return 0;
}
''',
    ".ts": '''\
// TypeScript
// Generated by STRIX

function greet(name: string): string {
    return `Hello, ${name}!`;
}

console.log(greet("Boss"));
''',
    ".sql": '''\
-- SQL Script
-- Generated by STRIX

CREATE TABLE users (
    id   INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE
);
''',
    ".txt": "Hello, Boss!\nCreated by STRIX.\n",
    ".md":  "# Project\n\nGenerated by STRIX.\n",
}

EXT_MAP = {
    "python": ".py", "py": ".py",
    "java": ".java",
    "javascript": ".js", "js": ".js",
    "html": ".html",
    "css": ".css",
    "typescript": ".ts", "ts": ".ts",
    "cpp": ".cpp", "c++": ".cpp",
    "c": ".c",
    "sql": ".sql",
    "text": ".txt", "txt": ".txt",
    "markdown": ".md", "md": ".md",
}

def _get_real_desktop() -> str:
    """Get the REAL desktop path — works even with OneDrive redirection."""
    # 1. Try Windows registry (most reliable)
    try:
        import winreg
        with winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders"
        ) as key:
            raw, _ = winreg.QueryValueEx(key, "Desktop")
            # Expand environment variables like %USERPROFILE%
            return os.path.expandvars(raw)
    except Exception:
        pass
    # 2. Try OneDrive path (common on Windows 10/11)
    onedrive_desktop = os.path.join(os.path.expanduser("~"), "OneDrive", "Desktop")
    if os.path.isdir(onedrive_desktop):
        return onedrive_desktop
    # 3. Fallback to classic path
    return os.path.join(os.path.expanduser("~"), "Desktop")

DESKTOP = _get_real_desktop()


def _get_starter(filename: str, hint: str = "") -> str:
    """Return starter code for a file based on extension or hint."""
    ext = os.path.splitext(filename)[1].lower()
    if not ext and hint:
        ext = EXT_MAP.get(hint.lower(), ".txt")
    return STARTERS.get(ext, STARTERS[".txt"])


def _resolve_path(path_str: str) -> str:
    """
    Resolve user path hints to real paths.
    'desktop' → C:\\Users\\...\\Desktop
    'E' or 'E drive' → E:\\
    """
    p = path_str.strip().strip('"').strip("'")
    if p.lower() in ("desktop", "my desktop"):
        return DESKTOP
    if len(p) == 1 and p.isalpha():
        return p.upper() + ":\\"
    if re.match(r'^[A-Za-z]$', p):
        return p.upper() + ":\\"
    if re.match(r'^[A-Za-z]:', p):
        return p
    # Default to desktop
    return os.path.join(DESKTOP, p)


# ── Rule-based parser (fast, no LLM needed) ──────────────────

def _parse_with_rules(text: str) -> list:
    """
    Parse common patterns without LLM.
    Returns list of step dicts or empty list if can't parse.
    """
    tl = text.lower()
    steps = []

    # ── Pattern: "create folder X with files A B C" ──────────
    # e.g. "make folder first_website with html css js files"
    folder_match = re.search(
        r'(?:create|make|new)\s+(?:a\s+)?folder\s+(?:named?\s+|called\s+)?([a-z0-9_\-\s]+?)(?:\s+(?:with|containing|and\s+add|in\s+it)|$)',
        tl
    )
    path_match = re.search(
        r'(?:in\s+|at\s+|on\s+|directory\s+)?([a-z](?:\s+drive)?|desktop)',
        tl
    )

    if folder_match:
        raw_folder = folder_match.group(1).strip().replace(" ", "_")
        base_path  = _resolve_path(path_match.group(1)) if path_match else DESKTOP
        folder_path = os.path.join(base_path, raw_folder)

        steps.append({
            "action": "create_folder_path",
            "params": {"path": folder_path},
            "description": f"Create folder {raw_folder}"
        })

        # Detect which files to create
        for lang, ext in EXT_MAP.items():
            if lang in tl and ext not in [s.get("params",{}).get("filename","")[-len(ext):]
                                           for s in steps]:
                fname = _lang_filename(lang, raw_folder)
                steps.append({
                    "action": "create_file_at_path",
                    "params": {
                        "path": os.path.join(folder_path, fname),
                        "content": _get_starter(fname, lang)
                    },
                    "description": f"Create {fname}"
                })

    return steps


def _lang_filename(lang: str, project_name: str = "main") -> str:
    """Return a sensible filename for a language."""
    name = project_name.split("_")[0].lower()
    mapping = {
        "python": "main.py", "py": "main.py",
        "java": "Main.java",
        "javascript": "script.js", "js": "script.js",
        "html": "index.html",
        "css": "style.css",
        "typescript": "index.ts", "ts": "index.ts",
        "cpp": "main.cpp", "c++": "main.cpp",
        "c": "main.c",
        "sql": "database.sql",
    }
    return mapping.get(lang, f"{name}.txt")


# ── LLM-based parser (for complex requests) ──────────────────

PLANNER_SYSTEM = """You are a task planner for STRIX AI.
Convert the user request into a JSON array of steps.
Each step must have exactly these fields:
  "action": one of [create_folder_path, create_file_at_path, open_app, get_system_status, get_weather, get_news, llm_response]
  "params": object with action-specific fields
  "description": short human-readable label

For create_folder_path: params = {"path": "full absolute path"}
For create_file_at_path: params = {"path": "full absolute path to file", "content": "starter code"}
For open_app: params = {"app": "app name"}
For llm_response: params = {"prompt": "question", "model": "reasoning"}

Rules:
- Use C:\\Users\\Public\\Desktop for desktop paths if unsure of username
- Always use double backslashes in paths: E:\\\\MyFolder
- For HTML+CSS+JS projects always create all 3 files
- Return ONLY the JSON array, no explanation, no markdown
"""


def _parse_with_llm(text: str) -> list:
    """Use llama3.1 to parse complex requests into steps."""
    try:
        from models.llm_interface import _call_ollama
        prompt = f"Convert this request into a JSON step plan:\n\n{text}"
        raw = _call_ollama("llama3.1", prompt, system=PLANNER_SYSTEM, stream=False)

        # Extract JSON from response
        raw = raw.strip()
        # Remove markdown fences if present
        raw = re.sub(r'^```(?:json)?\s*', '', raw, flags=re.MULTILINE)
        raw = re.sub(r'\s*```$', '', raw, flags=re.MULTILINE)

        # Find JSON array
        match = re.search(r'\[[\s\S]*\]', raw)
        if match:
            steps = json.loads(match.group())
            return steps
    except Exception as e:
        print(f"[Planner] LLM parse failed: {e}")
    return []


# ── Main planner function ─────────────────────────────────────

def build_plan(text: str) -> dict:
    """
    Main entry point. Returns a plan dict for executor.py.
    Tries rule-based first (fast), falls back to LLM if needed.
    """
    tl = text.lower()

    # Try rule-based first
    steps = _parse_with_rules(text)

    # If rule-based got nothing or request seems very complex → use LLM
    complex_indicators = [
        "and", "also", "then", "after that", "followed by",
        "multiple", "three", "four", "five", "several",
    ]
    is_complex = sum(1 for w in complex_indicators if w in tl) >= 2

    if not steps or (is_complex and len(steps) < 2):
        print("[Planner] Using LLM to parse complex request...")
        llm_steps = _parse_with_llm(text)
        if llm_steps:
            steps = llm_steps

    if not steps:
        # Absolute fallback — send to LLM as chat
        return {
            "tasks": [{"id":1, "action":"llm_response",
                       "description": text,
                       "params": {"prompt": text, "model": "reasoning"}}],
            "summary": "fallback"
        }

    # Convert steps to executor task format
    tasks = []
    for i, step in enumerate(steps, 1):
        tasks.append({
            "id": i,
            "action": step.get("action", "llm_response"),
            "description": step.get("description", f"Step {i}"),
            "params": step.get("params", {}),
        })

    return {"tasks": tasks, "summary": f"{len(tasks)} steps"}


# ── Is this a multi-step request? ────────────────────────────

def is_multi_step(tl: str) -> bool:
    """
    Detect if the request needs multi-step planning.
    Called from brain_core before routing.
    """
    multi_indicators = [
        # File + folder combos
        ("folder", "file"), ("folder", "html"), ("folder", "css"),
        ("folder", "javascript"), ("folder", "python"), ("folder", "java"),
        ("directory", "file"), ("directory", "create"),
        # Multiple files
        ("html", "css"), ("html", "javascript"), ("css", "javascript"),
        # Explicit sequencing
        ("create", "then"), ("make", "and then"), ("first", "then"),
        ("and also", "create"), ("and add", "file"),
    ]
    return any(all(w in tl for w in pair) for pair in multi_indicators)